name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t alexeytozik/my-django-app .

      - name: Push Docker image
        run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker push alexeytozik/my-django-app
      

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging
        run: |
          docker pull alexeytozik/my-django-app:latest
          docker run -d -p 8000:8000 my-django-app

  deploy-production:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: |
          docker pull alexeytozik/my-django-app:latest
          docker run -d -p 8000:8000 my-django-app